; generated by compiler

extern printf
; begin asm
format db '%u', 0
; end asm
; begin func main
global main
main:
enter 0, 0
sub esp, 4 ; declare var a
mov eax, 0 ; eax = 0
mov dword [ebp-4], eax ; dword [ebp-4] = eax
; begin asm

        push dword [ebp-4]
        push format
        call printf
        add esp, 12

        mov eax, 0
    
; end asm
leave
ret
; end func main
